import { Inter } from "next/font/google";
import "./globals.css";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Optimus Recruitment",
  description: "Generated by Youssef Sameh",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        <link rel="icon" href="/icon.png" />
      </head>
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}
